-- all empty strings in the table will be set to nil
return {
    id = 1,
    username = "sytses",
    name = "Sid Sijbrandij",
    state = "active",
    locked = false,
    avatar_url = "https://secure.gravatar.com/avatar/adcd204e48241a6528220c7450334cc5ffab2ea1c6a89d3d0ada01d01ed2b49e?s=80&d=identicon",
    web_url = "https://gitlab.com/sytses",
    created_at = "2012-09-14T14:10:29.000Z",
    bio = "",
    location = "",
    public_email = "",
    skype = "",
    linkedin = "",
    twitter = "sytses",
    discord = "",
    website_url = "",
    organization = "",
    job_title = "",
    pronouns = nil,
    bot = false,
    work_information = nil,
    followers = 129,
    following = 0,
    is_followed = false,
    local_time = nil
}
