-- all empty strings in the table will be set to nil
return {
    url = "https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/27",
    repository_url = "https://api.github.com/repos/Kaiser-Yang/blink-cmp-git",
    labels_url = "https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/27/labels{/name}",
    comments_url = "https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/27/comments",
    events_url = "https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/27/events",
    html_url = "https://github.com/Kaiser-Yang/blink-cmp-git/issues/27",
    id = 2840795137,
    node_id = "I_kwDONn0LzM6pUxgB",
    number = 27,
    title = "[Feature Request]: close issue as `not planned` support and states for pr and issues",
    user = {
        login = "MuntasirSZN",
        id = 161931072,
        node_id = "U_kgDOCabfQA",
        avatar_url = "https://avatars.githubusercontent.com/u/161931072?v=4",
        gravatar_id = nil,
        url = "https://api.github.com/users/MuntasirSZN",
        html_url = "https://github.com/MuntasirSZN",
        followers_url = "https://api.github.com/users/MuntasirSZN/followers",
        following_url = "https://api.github.com/users/MuntasirSZN/following{/other_user}",
        gists_url = "https://api.github.com/users/MuntasirSZN/gists{/gist_id}",
        starred_url = "https://api.github.com/users/MuntasirSZN/starred{/owner}{/repo}",
        subscriptions_url = "https://api.github.com/users/MuntasirSZN/subscriptions",
        organizations_url = "https://api.github.com/users/MuntasirSZN/orgs",
        repos_url = "https://api.github.com/users/MuntasirSZN/repos",
        events_url = "https://api.github.com/users/MuntasirSZN/events{/privacy}",
        received_events_url = "https://api.github.com/users/MuntasirSZN/received_events",
        type = "User",
        user_view_type = "public",
        site_admin = false
    },
    labels = {},
    state = "closed",
    locked = false,
    assignee = nil,
    assignees = {},
    milestone = nil,
    comments = 29,
    created_at = "2025-02-09T16:34:55Z",
    updated_at = "2025-02-10T13:01:29Z",
    closed_at = "2025-02-10T13:01:28Z",
    author_association = "NONE",
    sub_issues_summary = {
        total = 0,
        completed = 0,
        percent_completed = 0
    },
    active_lock_reason = nil,
    body = "title ;) Currently, there is open and closed. Can we do open, closed as completed and closed as not planned?",
    closed_by = {
        login = "Kaiser-Yang",
        id = 58209855,
        node_id = "MDQ6VXNlcjU4MjA5ODU1",
        avatar_url = "https://avatars.githubusercontent.com/u/58209855?v=4",
        gravatar_id = nil,
        url = "https://api.github.com/users/Kaiser-Yang",
        html_url = "https://github.com/Kaiser-Yang",
        followers_url = "https://api.github.com/users/Kaiser-Yang/followers",
        following_url = "https://api.github.com/users/Kaiser-Yang/following{/other_user}",
        gists_url = "https://api.github.com/users/Kaiser-Yang/gists{/gist_id}",
        starred_url = "https://api.github.com/users/Kaiser-Yang/starred{/owner}{/repo}",
        subscriptions_url = "https://api.github.com/users/Kaiser-Yang/subscriptions",
        organizations_url = "https://api.github.com/users/Kaiser-Yang/orgs",
        repos_url = "https://api.github.com/users/Kaiser-Yang/repos",
        events_url = "https://api.github.com/users/Kaiser-Yang/events{/privacy}",
        received_events_url = "https://api.github.com/users/Kaiser-Yang/received_events",
        type = "User",
        user_view_type = "public",
        site_admin = false
    },
    reactions = {
        url = "https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/27/reactions",
        total_count = 0,
        ["+1"] = 0,
        ["-1"] = 0,
        laugh = 0,
        hooray = 0,
        confused = 0,
        heart = 0,
        rocket = 0,
        eyes = 0
    },
    timeline_url = "https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/27/timeline",
    performed_via_github_app = nil,
    state_reason = "completed"
}
