-- all empty strings in the table will be set to nil
return {
    login = 'Kaiser-Yang',
    id = 58209855,
    node_id = 'MDQ6VXNlcjU4MjA5ODU1',
    avatar_url = 'https://avatars.githubusercontent.com/u/58209855?v=4',
    gravatar_id = nil,
    url = 'https://api.github.com/users/Kaiser-Yang',
    html_url = 'https://github.com/Kaiser-Yang',
    followers_url = 'https://api.github.com/users/Kaiser-Yang/followers',
    following_url = 'https://api.github.com/users/Kaiser-Yang/following{/other_user}',
    gists_url = 'https://api.github.com/users/Kaiser-Yang/gists{/gist_id}',
    starred_url = 'https://api.github.com/users/Kaiser-Yang/starred{/owner}{/repo}',
    subscriptions_url = 'https://api.github.com/users/Kaiser-Yang/subscriptions',
    organizations_url = 'https://api.github.com/users/Kaiser-Yang/orgs',
    repos_url = 'https://api.github.com/users/Kaiser-Yang/repos',
    events_url = 'https://api.github.com/users/Kaiser-Yang/events{/privacy}',
    received_events_url = 'https://api.github.com/users/Kaiser-Yang/received_events',
    type = 'User',
    user_view_type = 'public',
    site_admin = false,
    name = 'Qingzhou Yue',
    company = nil,
    blog = 'https://kaiser-yang.github.io/',
    location = 'China',
    email = nil,
    hireable = true,
    bio = nil,
    twitter_username = nil,
    public_repos = 27,
    public_gists = 0,
    followers = 3,
    following = 1,
    created_at = '2019-11-26T08:36:10Z',
    updated_at = '2025-02-08T13:06:26Z',
}
