-- all empty strings in the table will be set to nil
return {
    url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/29',
    id = 2326119635,
    node_id = 'PR_kwDONn0LzM6KpcTT',
    html_url = 'https://github.com/Kaiser-Yang/blink-cmp-git/pull/29',
    diff_url = 'https://github.com/Kaiser-Yang/blink-cmp-git/pull/29.diff',
    patch_url = 'https://github.com/Kaiser-Yang/blink-cmp-git/pull/29.patch',
    issue_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/29',
    number = 29,
    state = 'open',
    locked = false,
    title = 'v2.0.0',
    user = {
        login = 'Kaiser-Yang',
        id = 58209855,
        node_id = 'MDQ6VXNlcjU4MjA5ODU1',
        avatar_url = 'https://avatars.githubusercontent.com/u/58209855?v=4',
        gravatar_id = nil,
        url = 'https://api.github.com/users/Kaiser-Yang',
        html_url = 'https://github.com/Kaiser-Yang',
        followers_url = 'https://api.github.com/users/Kaiser-Yang/followers',
        following_url = 'https://api.github.com/users/Kaiser-Yang/following{/other_user}',
        gists_url = 'https://api.github.com/users/Kaiser-Yang/gists{/gist_id}',
        starred_url = 'https://api.github.com/users/Kaiser-Yang/starred{/owner}{/repo}',
        subscriptions_url = 'https://api.github.com/users/Kaiser-Yang/subscriptions',
        organizations_url = 'https://api.github.com/users/Kaiser-Yang/orgs',
        repos_url = 'https://api.github.com/users/Kaiser-Yang/repos',
        events_url = 'https://api.github.com/users/Kaiser-Yang/events{/privacy}',
        received_events_url = 'https://api.github.com/users/Kaiser-Yang/received_events',
        type = 'User',
        user_view_type = 'public',
        site_admin = false,
    },
    body = [[
Break feature for those who do some customization.

- [ ] using `api` for `github`, fallback to `curl`
- [ ] using `api` for `gitlab`, fallback to `curl`
- [ ] `before_reloading_cache` callback for cache reloading command

This will close #28 .

This will close #30 .
]],
    created_at = '2025-02-10T13:52:32Z',
    updated_at = '2025-02-11T01:28:53Z',
    closed_at = nil,
    merged_at = nil,
    merge_commit_sha = '6b867a5045e05d72e77af446e0f48fcecd03cd2d',
    assignee = {
        login = 'Kaiser-Yang',
        id = 58209855,
        node_id = 'MDQ6VXNlcjU4MjA5ODU1',
        avatar_url = 'https://avatars.githubusercontent.com/u/58209855?v=4',
        gravatar_id = nil,
        url = 'https://api.github.com/users/Kaiser-Yang',
        html_url = 'https://github.com/Kaiser-Yang',
        followers_url = 'https://api.github.com/users/Kaiser-Yang/followers',
        following_url = 'https://api.github.com/users/Kaiser-Yang/following{/other_user}',
        gists_url = 'https://api.github.com/users/Kaiser-Yang/gists{/gist_id}',
        starred_url = 'https://api.github.com/users/Kaiser-Yang/starred{/owner}{/repo}',
        subscriptions_url = 'https://api.github.com/users/Kaiser-Yang/subscriptions',
        organizations_url = 'https://api.github.com/users/Kaiser-Yang/orgs',
        repos_url = 'https://api.github.com/users/Kaiser-Yang/repos',
        events_url = 'https://api.github.com/users/Kaiser-Yang/events{/privacy}',
        received_events_url = 'https://api.github.com/users/Kaiser-Yang/received_events',
        type = 'User',
        user_view_type = 'public',
        site_admin = false,
    },
    assignees = {
        {
            login = 'Kaiser-Yang',
            id = 58209855,
            node_id = 'MDQ6VXNlcjU4MjA5ODU1',
            avatar_url = 'https://avatars.githubusercontent.com/u/58209855?v=4',
            gravatar_id = nil,
            url = 'https://api.github.com/users/Kaiser-Yang',
            html_url = 'https://github.com/Kaiser-Yang',
            followers_url = 'https://api.github.com/users/Kaiser-Yang/followers',
            following_url = 'https://api.github.com/users/Kaiser-Yang/following{/other_user}',
            gists_url = 'https://api.github.com/users/Kaiser-Yang/gists{/gist_id}',
            starred_url = 'https://api.github.com/users/Kaiser-Yang/starred{/owner}{/repo}',
            subscriptions_url = 'https://api.github.com/users/Kaiser-Yang/subscriptions',
            organizations_url = 'https://api.github.com/users/Kaiser-Yang/orgs',
            repos_url = 'https://api.github.com/users/Kaiser-Yang/repos',
            events_url = 'https://api.github.com/users/Kaiser-Yang/events{/privacy}',
            received_events_url = 'https://api.github.com/users/Kaiser-Yang/received_events',
            type = 'User',
            user_view_type = 'public',
            site_admin = false,
        },
    },
    requested_reviewers = {},
    requested_teams = {},
    labels = {
        {
            id = 7980962409,
            node_id = 'LA_kwDONn0LzM8AAAAB27PSaQ',
            url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/labels/enhancement',
            name = 'enhancement',
            color = 'a2eeef',
            default = true,
            description = 'New feature or request',
        },
    },
    milestone = nil,
    draft = true,
    commits_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/29/commits',
    review_comments_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/29/comments',
    review_comment_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/comments{/number}',
    comments_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/29/comments',
    statuses_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/statuses/55cccdf04c93f07be923f16eb6341a524124f647',
    head = {
        label = 'Kaiser-Yang:refactor-api',
        ref = 'refactor-api',
        sha = '55cccdf04c93f07be923f16eb6341a524124f647',
        user = {
            login = 'Kaiser-Yang',
            id = 58209855,
            node_id = 'MDQ6VXNlcjU4MjA5ODU1',
            avatar_url = 'https://avatars.githubusercontent.com/u/58209855?v=4',
            gravatar_id = nil,
            url = 'https://api.github.com/users/Kaiser-Yang',
            html_url = 'https://github.com/Kaiser-Yang',
            followers_url = 'https://api.github.com/users/Kaiser-Yang/followers',
            following_url = 'https://api.github.com/users/Kaiser-Yang/following{/other_user}',
            gists_url = 'https://api.github.com/users/Kaiser-Yang/gists{/gist_id}',
            starred_url = 'https://api.github.com/users/Kaiser-Yang/starred{/owner}{/repo}',
            subscriptions_url = 'https://api.github.com/users/Kaiser-Yang/subscriptions',
            organizations_url = 'https://api.github.com/users/Kaiser-Yang/orgs',
            repos_url = 'https://api.github.com/users/Kaiser-Yang/repos',
            events_url = 'https://api.github.com/users/Kaiser-Yang/events{/privacy}',
            received_events_url = 'https://api.github.com/users/Kaiser-Yang/received_events',
            type = 'User',
            user_view_type = 'public',
            site_admin = false,
        },
        repo = {
            id = 914164684,
            node_id = 'R_kgDONn0LzA',
            name = 'blink-cmp-git',
            full_name = 'Kaiser-Yang/blink-cmp-git',
            private = false,
            owner = {
                login = 'Kaiser-Yang',
                id = 58209855,
                node_id = 'MDQ6VXNlcjU4MjA5ODU1',
                avatar_url = 'https://avatars.githubusercontent.com/u/58209855?v=4',
                gravatar_id = nil,
                url = 'https://api.github.com/users/Kaiser-Yang',
                html_url = 'https://github.com/Kaiser-Yang',
                followers_url = 'https://api.github.com/users/Kaiser-Yang/followers',
                following_url = 'https://api.github.com/users/Kaiser-Yang/following{/other_user}',
                gists_url = 'https://api.github.com/users/Kaiser-Yang/gists{/gist_id}',
                starred_url = 'https://api.github.com/users/Kaiser-Yang/starred{/owner}{/repo}',
                subscriptions_url = 'https://api.github.com/users/Kaiser-Yang/subscriptions',
                organizations_url = 'https://api.github.com/users/Kaiser-Yang/orgs',
                repos_url = 'https://api.github.com/users/Kaiser-Yang/repos',
                events_url = 'https://api.github.com/users/Kaiser-Yang/events{/privacy}',
                received_events_url = 'https://api.github.com/users/Kaiser-Yang/received_events',
                type = 'User',
                user_view_type = 'public',
                site_admin = false,
            },
            html_url = 'https://github.com/Kaiser-Yang/blink-cmp-git',
            description = 'Git source for blink.cmp',
            fork = false,
            url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git',
            forks_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/forks',
            keys_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/keys{/key_id}',
            collaborators_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/collaborators{/collaborator}',
            teams_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/teams',
            hooks_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/hooks',
            issue_events_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/events{/number}',
            events_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/events',
            assignees_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/assignees{/user}',
            branches_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/branches{/branch}',
            tags_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/tags',
            blobs_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/git/blobs{/sha}',
            git_tags_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/git/tags{/sha}',
            git_refs_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/git/refs{/sha}',
            trees_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/git/trees{/sha}',
            statuses_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/statuses/{sha}',
            languages_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/languages',
            stargazers_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/stargazers',
            contributors_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/contributors',
            subscribers_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/subscribers',
            subscription_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/subscription',
            commits_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/commits{/sha}',
            git_commits_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/git/commits{/sha}',
            comments_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/comments{/number}',
            issue_comment_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/comments{/number}',
            contents_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/contents/{+path}',
            compare_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/compare/{base}...{head}',
            merges_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/merges',
            archive_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/{archive_format}{/ref}',
            downloads_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/downloads',
            issues_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues{/number}',
            pulls_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls{/number}',
            milestones_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/milestones{/number}',
            notifications_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/notifications{?since,all,participating}',
            labels_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/labels{/name}',
            releases_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/releases{/id}',
            deployments_url = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/deployments',
            created_at = '2025-01-09T04:17:45Z',
            updated_at = '2025-02-10T12:36:50Z',
            pushed_at = '2025-02-10T15:33:45Z',
            git_url = 'git://github.com/Kaiser-Yang/blink-cmp-git.git',
            ssh_url = 'git@github.com:Kaiser-Yang/blink-cmp-git.git',
            clone_url = 'https://github.com/Kaiser-Yang/blink-cmp-git.git',
            svn_url = 'https://github.com/Kaiser-Yang/blink-cmp-git',
            homepage = nil,
            size = 599,
            stargazers_count = 25,
            watchers_count = 25,
            language = 'Lua',
            has_issues = true,
            has_projects = true,
            has_downloads = true,
            has_wiki = true,
            has_pages = false,
            has_discussions = false,
            forks_count = 4,
            mirror_url = nil,
            archived = false,
            disabled = false,
            open_issues_count = 6,
            license = {
                key = 'mit',
                name = 'MIT License',
                spdx_id = 'MIT',
                url = 'https://api.github.com/licenses/mit',
                node_id = 'MDc6TGljZW5zZTEz',
            },
            allow_forking = true,
            is_template = false,
            web_commit_signoff_required = false,
            topics = {},
            visibility = 'public',
            forks = 4,
            open_issues = 6,
            watchers = 25,
            default_branch = 'master',
        },
    },
    _links = {
        self = { href = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/29' },
        html = { href = 'https://github.com/Kaiser-Yang/blink-cmp-git/pull/29' },
        issue = { href = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/29' },
        comments = {
            href = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/issues/29/comments',
        },
        review_comments = {
            href = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/29/comments',
        },
        review_comment = {
            href = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/comments{/number}',
        },
        commits = {
            href = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/pulls/29/commits',
        },
        statuses = {
            href = 'https://api.github.com/repos/Kaiser-Yang/blink-cmp-git/statuses/55cccdf04c93f07be923f16eb6341a524124f647',
        },
    },
    author_association = 'OWNER',
    auto_merge = nil,
    active_lock_reason = nil,
}
